### PR TITLE
try safe handle external handle

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
A random ci fail: https://github.com/zhaozg/luv/actions/runs/11754015398/job/32747531427

**Review by rdw-software — COMMENTED** [review]
Didn't measure performance as it's unlikely to matter, but the loop can be shared without crashing when using the patch :)

**Comment by zhaozg** [comment]
> Didn't measure performance as it's unlikely to matter, but the loop can be shared without crashing when using the patch :)

Thanks for your check, I'll update when I have free time, in this week.

**Comment by clason** [comment]
Sorry for necro-posting, but can you comment on why these tests are built unconditionally? They break Neovim's build on Ubuntu (clang) and Windows: https://github.com/neovim/neovim/actions/runs/12924924457/job/36044861041?pr=32174

**Comment by squeek502** [comment]
> but can you comment on why these tests are built unconditionally?

Just an oversight, sorry. Will be fixed by https://github.com/luvit/luv/pull/752

**Pull request merged**
