### PR TITLE
add new API and fix minor warning

### PR DESCRIPTION
**Pull request by zhaozg**
for last libuv 1.16.0

### CODE REVIEW

**Comment by zhaozg** [comment]
@rphillips @creationix please review

**Comment by rphillips** [comment]
hmm. there are a couple timeouts on travis, but I don't think it is related to the PR

**Comment by squeek502** [comment]
The timeouts seem to be consistent on Travis's Linux builds. This is the test that's timing out: https://github.com/luvit/luv/blob/master/tests/test-tcp.lua#L2-L27

**Comment by justinmk** [comment]
Travis removed ipv6 support, see https://github.com/neovim/neovim/pull/7478

**Comment by squeek502** [comment]
Thanks for the heads up @justinmk, added a PR to allow ipv6 to fail: #268

**Comment by creationix** [comment]
So this should pass now if it's rebased right?

**Comment by zhaozg** [comment]
rebased

**Comment by creationix** [comment]
Thanks!

**Pull request merged**
