### PR TITLE
update luv to support latest libuv

### PR DESCRIPTION
**Pull request by zhaozg**

### CODE REVIEW

**Comment by zhaozg** [comment]
please check at https://github.com/libuv/libuv/blob/v1.x/docs/src/misc.rst#api and https://github.com/libuv/libuv/blob/v1.x/docs/src/errors.rst#api

**Comment by creationix** [comment]
oh nice, they added environment variable functions!

**Comment by jdonaldson** [comment]
It would be nice to get a version bump for luv.  I can drop a separate environment management library from my project dependencies.

**Comment by creationix** [comment]
Good point, I had forgot about this.  I'm heading to Houston to help with volunteer flood cleanup this weekend so I'm not sure I'll get a build out.  If I don't, feel free to ping me again next week.

**Comment by jdonaldson** [comment]
Oh wow, don't worry about this then.  Good luck over there, I have friends and family down there too.  Thanks for helping out!

**Pull request merged**
