### PR TITLE
enhance threadpool and bug fix

### PR DESCRIPTION
**Pull request by zhaozg**
1. support entry_code reuse, reduce loadstring times
2. fix bug create uv_key_t to hold lua vm
3. fix bug when threadpool(uv.new_work) use wrong stack index

### CODE REVIEW

**Comment by zhaozg** [comment]
continue https://github.com/luvit/luv/pull/179

**Comment by zhaozg** [comment]
After merge, I can do some RP on luvit

**Comment by rphillips** [comment]
@zhaozg do you need a release as well?

**Comment by zhaozg** [comment]
@rphillips just at free you time, I use source code directly now.

**Pull request merged**
