### PR TITLE
Update submodule

### PR DESCRIPTION
**Pull request by zhaozg**
* update libuv to v1.40.0
* update LuaJIT

### CODE REVIEW

**Comment by squeek502** [comment]
Missing bindings: [`uv_timer_get_due_in`](http://docs.libuv.org/en/v1.x/timer.html#c.uv_timer_get_due_in)

**Comment by zhaozg** [comment]
> Missing bindings: [`uv_timer_get_due_in`](http://docs.libuv.org/en/v1.x/timer.html#c.uv_timer_get_due_in)

Done

**Comment by zhaozg** [comment]
I report a bug to libuv at https://github.com/libuv/libuv/issues/3020

**Comment by squeek502** [comment]
Created a pull request to your branch with some improvements: https://github.com/luvit/luv/pull/518

**Review by squeek502 — APPROVED** [review]

**Pull request merged**
