### PR TITLE
bump luajit 21

### PR DESCRIPTION
**Pull request by rphillips**
trying out a luajit 2.1 bump

### CODE REVIEW

**Comment by joerg-krause** [comment]
Is there any need to switch to (unstable) luajit 2.1? I would rather see luv to depend on a stable version.

**Comment by creationix** [comment]
I want to keep the default build on stable luajit, but I'm all for adding the option to use luajit 2.1.  I wonder how we can support both at the same time.

**Comment by DBarney** [comment]
I haven't had any issues with 2.1, in fact its nice to be able to use the built in profiler and generate flame graphs to optimize hot code paths.

The 2.1 branch is mostly stable, I saw on the mailing list a few weeks ago that they are considering making a 2.1 release soon, just have to finish off a few last features.

maybe instead of making 2.1 the default, it could just be a build option?

**Comment by joerg-krause** [comment]
If it's only about performance I would stick to luajit 2.0.4 until luajit 2.1 is finally released.

>  I wonder how we can support both at the same time.

How about a new branch for luajit 2.1?

**Comment by rphillips** [comment]
I cherry-picked my 32bit tests commit to a new PR.

**Pull request closed without merging**
