### PR TITLE
Standardize/factor out common result handling code

### PR DESCRIPTION
**Pull request by squeek502**
This is a preparatory step that will make #400 much easier but is probably a good idea regardless of what we end up deciding to do there.

### CODE REVIEW

**Comment by SinisterRectus** [comment]
The only issue I see here is that some of these functions return an integer as part of their normal operation. If we decide to change the behavior for returning success status, we wouldn't want to include these functions.

**Comment by squeek502** [comment]
> some of these functions return an integer as part of their normal operation

Could you provide an example of one? I'll double check, but I thought the pattern I replaced wouldn't include any of those.

**Comment by SinisterRectus** [comment]
The ones I can find are:
- `send_buffer_size` (if not setting the size)
- `recv_buffer_size` (if not setting the size)
- `backend_fd`
- `try_write`

I notice also that `backend_timeout` is a function that can return -1 successfully. That is already set up to not push an error though.

**Comment by squeek502** [comment]
`send_buffer_size`/`recv_buffer_size` are bugged: https://github.com/luvit/luv/issues/404

**Comment by squeek502** [comment]
* `send_buffer_size`: fixed by #405, now only uses luv_result in the setter case
* `recv_buffer_size`: fixed by #405, now only uses luv_result in the setter case
* `backend_fd`: this is also bound wrong--it never returns a UV_E error code, it just returns -1 when unsupported (on Windows). It's now unchanged in this PR, will address it in a separate PR
* `try_write`: Updated this to use better variable names so that it doesn't get mistaken for the luv_result pattern

Will double check the rest of the changes in this PR to make sure that there are no other functions that shouldn't be using `luv_result` before merging.

**Comment by squeek502** [comment]
Ok, I'm now confident that this only affects functions that only return their success/error state. Will squash/merge if there are no other comments.

**Comment by SinisterRectus** [comment]
I'll make one more pass through and give it an okay later.

**Comment by SinisterRectus** [comment]
Can you check that `fileno` is operating properly? Other than that, looks good to go.

**Comment by squeek502** [comment]
Made a separate issue for `fileno` (#408) since it definitely should not be using `luv_result`.

**Pull request merged**
