### PR TITLE
Change fs_scandir_next() to return two values instead of a table

### LINKED ISSUE #201: Function fs_scandir_next creates tables unnecessarily
I think `fs_scandir_next` is being unnecessarily wasteful here: https://github.com/luvit/luv/blob/master/src/fs.c#L406-L436

Instead of creating a table at each call it could simply return 2 values (name and type). For programs that scan lots of big dirs, this is going to be much faster, and more importantly won't create a lot of garbage and put a lot of pressure on the GC.

The resulting code is also simpler to use. A table only adds complexity here, IMHO.

### PR DESCRIPTION
**Pull request by tbastos**
Changes:
- Closes #201 (Change `fs_scandir_next()` to return two values instead of a table)
- Increase interval tolerance in test "timer - timeout with interval" in order to avoid random fails on AppVeyor and slow CI servers. Increased from 50ms to 100ms.

### CODE REVIEW

**Comment by tbastos** [comment]
PS: do you mind uploading a new luarocks release after this? I'll need it for my project and it can't be done with a PR, unfortunately. Thanks!

**Comment by creationix** [comment]
It says there are conflicts.  Can you rebase the PR with master?

**Comment by tbastos** [comment]
Conflict fixed. Please don't forget the new luarocks release ;)

**Comment by creationix** [comment]
Ok, I think it's published. http://luarocks.org/modules/creationix/luv/1.8.0-1

**Comment by tbastos** [comment]
Thanks! My AppVeyor is almost functional again :)

I thought you'd bump the version number since there were breaking API changes, but it doesn't really matter for me.

**Comment by creationix** [comment]
I would, but the version number matches the upstream libuv version which we didn't change.

**Pull request merged**
