### PR TITLE
gc: setup a proper gc for the uv_loop

### PR DESCRIPTION
**Pull request by rphillips**
fixes: #193

### CODE REVIEW

**Comment by tarruda** [comment]
This seems to have fixed the problem. Can I do anything else to help getting this into the master branch and in a new luv release?

**Comment by rphillips** [comment]
Thanks for the help! Once I get an independent review from @creationix (most likely today), we will get this in and released.

**Comment by rphillips** [comment]
I forgot tim is off today. I'll roll a release.

**Comment by tarruda** [comment]
> Thanks for the help! Once I get an independent review from @creationix (most likely today), we will get this in and released.

Great, looking forward to it. Thanks for the amazing work on luv/luvi/luvit!

BTW I added the fixup commit so you could squash into your own with `git rebase -i --autosquash`, but its your call.

**Comment by rphillips** [comment]
1.7.4-5 is tagged, but we will need to wait for @creationix to push to luarocks. (I don't have access)

**Pull request merged**
