### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [code quality badges](https://lgtm.com/projects/g/luvit/luv/ci/#badges) to your project. They will indicate a very high code quality to potential users and contributors.
You can also check the alerts discovered by [LGTM](https://lgtm.com/projects/g/luvit/luv).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by zhaozg** [comment]
LGTM

Should we consider to merge this? @luvit/luvit-admin

**Comment by Kami** [comment]
I see no problems with merging this.

**Comment by squeek502** [comment]
It seems right now all of luv's LGTM warnings are from its submodules. @xcorail, any way to exclude submodules from the checks?

**Comment by zhaozg** [comment]
hi @squeek502 maybe https://lgtm.com/help/lgtm/lgtm.yml-configuration-file#path_classifiers

**Pull request merged**
