### PR TITLE
Add support for building luv as shared library

### PR DESCRIPTION
**Pull request by joerg-krause**
Allow to build luv as shared library for building external applications against luv.

### CODE REVIEW

**Comment by creationix** [comment]
Looks good.  I wonder why travis is failing.  Is this rebased against latest luv?  I changed the luajit version this morning.

**Comment by joerg-krause** [comment]
Yes, it is rebased on top of 929f8bf.

**Comment by joerg-krause** [comment]
Travis fails because of 6e2cacb6f4ebfcc50773d4179ddd010a89d2f8fd. The sources only exist in the luajit 2.1 branch.

**Comment by rphillips** [comment]
fixed in d7ce4dc

**Comment by creationix** [comment]
@rphillips Ah yes, sorry I forgot about that.

@joerg-krause if you rebase again with ryans fix, it should pass now.

**Pull request closed without merging**
