### PR TITLE
Clean up luv_state/luv_loop/etc comments and API

### PR DESCRIPTION
**Pull request by squeek502**
- Made luv_loop/luv_state ~~inline~~ functions instead of macros to make it more clear how they are meant to be used and give them type safety
- Updated the comments to match how things work now

### CODE REVIEW

**Comment by zhaozg** [comment]
ci broken ,maybe inline cause that

**Comment by squeek502** [comment]
Took out the inline keyword, just made them normal functions instead.

**Comment by rphillips** [comment]
`extern inline` might fix it.

**Comment by squeek502** [comment]
AFAIK `LUALIB_API` should actually resolve to `extern` on Linux where it was failing (and, confusingly, the build [succeeded on my fork](https://travis-ci.org/squeek502/luv/builds/559304421) but [failed in the PR](https://travis-ci.org/luvit/luv/jobs/559304480). MSVC would also need to use `__inline` instead for versions earlier than 2015 [see the previous appveyor failure](https://ci.appveyor.com/project/racker-buildbot/luv/builds/26006254). Is it worth it to wrestle the compilers for this inline hint?

**Comment by rphillips** [comment]
nope. not worth it.

**Comment by zhaozg** [comment]
Will more contine PRs

**Pull request merged**
