### PR TITLE
Update Lua to version 5.3.1

### PR DESCRIPTION
**Pull request by joerg-krause**

### CODE REVIEW

**Comment by creationix** [comment]
@joerg-krause does this failure look like it might be related to https://ci.appveyor.com/project/racker-buildbot/luv/branch/master/job/ktw1vebnduws8nbc ?

**Comment by joerg-krause** [comment]
No, I don't think so as the previous build was successful: https://ci.appveyor.com/project/racker-buildbot/luv/build/1.0.228.

**Comment by creationix** [comment]
Good point, I'll re-run the test and see if it was some transient issue.

**Comment by creationix** [comment]
Seems fine now. https://ci.appveyor.com/project/racker-buildbot/luv/build/1.0.230

**Pull request merged**
