### PR TITLE
lgtm.yml: classify deps as library files

### PR DESCRIPTION
**Pull request by squeek502**
See https://github.com/luvit/luv/pull/367#issuecomment-517863115

### CODE REVIEW

**Comment by zhaozg** [comment]
This can ignore submodule warning?

path_classifiers:
  library:
    - deps
    - exclude: deps/luaJIT
    - exclude: deps/libuv

**Comment by squeek502** [comment]
> This can ignore submodule warning?

Yes, I think so. Directories/files classified as `library` are ignored, and this PR should make it so that `deps` and all of its subdirectories are classified as `library`.

**Comment by zhaozg** [comment]
ok, that's fine

**Comment by squeek502** [comment]
It worked:
- https://lgtm.com/projects/g/luvit/luv/latest/files/?sort=name&dir=ASC&mode=heatmap&showExcluded=false
- https://lgtm.com/projects/g/luvit/luv/alerts/?mode=list

**Pull request merged**
