### PR TITLE
travis: Fix deploy step

### PR DESCRIPTION
**Pull request by squeek502**
Accidentally removed Luarocks installation from the deploy step in https://github.com/luvit/luv/pull/432

### CODE REVIEW

**Comment by zhaozg** [comment]
Shoud release 1.34.1-1?

**Comment by squeek502** [comment]
Yes, that would be the easiest way to do it.

**Comment by zhaozg** [comment]
You do or I do?

**Comment by squeek502** [comment]
I just did: https://github.com/luvit/luv/releases/tag/1.34.1-1

**Pull request merged**
