### PR TITLE
add basic thread support

### PR DESCRIPTION
**Pull request by zhaozg**
include #133

### CODE REVIEW

**Comment by rphillips** [comment]
This is awesome. A few test cases would be extremely nice.

**Comment by zhaozg** [comment]
some example https://github.com/zhaozg/luv/blob/master/examples/uvbook/queue-work.lua and https://github.com/zhaozg/luv/blob/master/examples/uvbook/thread-create.lua

**Comment by rphillips** [comment]
+1

**Comment by creationix** [comment]
@zhaozg is this safe to merge or did you want to work on it some more?

**Comment by zhaozg** [comment]
Please merge, It enough support to thread and simple threadpool.

**Comment by imzyxwvu** [comment]
I do not think it is a good idea to call string.dump instead of lua_dump.

**Comment by zhaozg** [comment]
>I do not think it is a good idea to call string.dump instead of lua_dump.

Accept, I will update

**Pull request merged**
